## Homework #4 ##

#### Chris Lamb NE 24####

Just as a general note for this iPython notebook for me, I'm running
this in Python Version 3.4.5 and Anaconda Version 2.3.0 so the 'print' syntax will include '(  )' which I don't think will work on any Python Version 2.X.X

In [1]:
from math import *
import numpy as np

#### `Example 1:` ####
An extended version of the conversion example in the ipython.ipynb that we
worked on in class.

In [2]:
def inches_to_meters(inches):
    meters = inches/39.4
    print (inches,'inches is equal to:', meters, 'meters.')
def feet_to_meters(feet):
    meters = (feet * 12)/39.4
    print (feet,'feet is equal to:', meters, 'meters.')
def meters_to_inches(meters):
    inches = 39 * meters
    print (meters,'meters is equal to:', inches, 'inches.')
def meters_to_feet(meters):
    feet = (39 * meters)/12
    print (meters,'meters is equal to:', feet, 'feet.')

In [3]:
inches_to_meters(120)

120 inches is equal to: 3.0456852791878175 meters.


In [4]:
feet_to_meters(10)

10 feet is equal to: 3.0456852791878175 meters.


In [5]:
meters_to_inches(3)

3 meters is equal to: 117 inches.


In [6]:
meters_to_feet(3)

3 meters is equal to: 9.75 feet.


I created functions instead of simple variables so that they can be called 
at any time in the future.

#### `Example 2:` ####
Using very simple if/else to find the closest city to a given point. The city will be a 3 element list that includes, the name of the city and the x and y coordinates. And the point for the final function will be a 2 element list that includes the x and y coordinates.

In [7]:
def closer_city(point, city1, city2):
    x1, y1 = city1[1], city1[2]
    x2, y2 = city2[1], city2[2]
    xp, yp = point[0], point[1]
    d1 = sqrt ((x1 - xp)**2 + (y1 - yp)**2)
    d2 = sqrt ((x2 - xp)**2 + (y2 - yp)**2)
    if d1 < d2:
        print ('The closest city is:',city1[0])
    else:
        print ('The closest city is:',city2[0])

In [8]:
current_loc = [37.8719, 122.2585]
new_york = ['New York', 40.7128, 74.0059]
boston = ['Boston', 42.3601, 71.0589]

In [9]:
closer_city(current_loc, new_york, boston)

The closest city is: New York


In [10]:
cairo = ['Cairo', 30.0444, -31.2357]
berlin = ['Berlin', 52.5200, 13.4050]

In [11]:
closer_city(current_loc, cairo, berlin)

The closest city is: Berlin


#### `Example 3` ####
Using now if/else and for loops to determine if a number is a prime number or a composite number.

In [12]:
def prime_checker(n):
    def is_prime(n):
        if n == 1:
            return False
        for i in range(2, n):
            if n % i == 0:
                return False
        return True
    if is_prime(n):
        print (n,"is a prime number.")
    else:
        print (n,"is a composite number.")

In [13]:
prime_checker(13)

13 is a prime number.


In [14]:
prime_checker(42)

42 is a composite number.


In [15]:
prime_checker(43592)

43592 is a composite number.


In [16]:
prime_checker(16699)

16699 is a prime number.


Note, I started to run the number 16699 to see if the prime checker worker for larger numbers (I already knew that it was prime). It took around 8 minutes for it to initially say that it was prime, why it did that I don't entirely know but everytime I've tried running it since it has happened as quick as the others. Incase it for some reason takes a while to work on your end, [here](http://i.imgur.com/WZiit5u.png) is a link with a screenshot of the completed job. 

#### `Example 4` ####
Now using numpy notation to take an array of numbers and scale the whole thing by another number n.

In [17]:
def array_scaler(array, n):
    scaler_length = len(array)
    scaling_matrix = np.ones((scaler_length,), dtype=np.int)
    scaler = scaling_matrix * n
    new_array = array * scaler
    print ('The array:\n',array,'\nscaled by',n, 'is:\n', new_array)

In [18]:
array = [1,2,3,4,5,6,7,8,9,10]

In [19]:
array_scaler(array, 10)

The array:
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
scaled by 10 is:
 [ 10  20  30  40  50  60  70  80  90 100]


In [20]:
array2 = [11,22,33,44,55,66,77,88,99,111]

In [21]:
array_scaler(array2, 17)

The array:
 [11, 22, 33, 44, 55, 66, 77, 88, 99, 111] 
scaled by 17 is:
 [ 187  374  561  748  935 1122 1309 1496 1683 1887]


In [22]:
array3 = [1002,1003,1004,1005,1006,1007]

In [23]:
array_scaler(array3, 65)

The array:
 [1002, 1003, 1004, 1005, 1006, 1007] 
scaled by 65 is:
 [65130 65195 65260 65325 65390 65455]
